# Generated by Django 5.2.6 on 2025-09-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sait_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['surname', 'name'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AddField(
            model_name='author',
            name='desc',
            field=models.CharField(default='Умер', verbose_name='Жив или нежив'),
        ),
        migrations.AlterField(
            model_name='author',
            name='birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['surname'], name='sait_app_au_surname_1866b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(condition=models.Q(('desc', 'Жив')), fields=('surname', 'bio'), name='unique_surname_bio'),
        ),
    ]
